#!/usr/bin/env bun
/**
 * Scaffold a new micro-niche lead gen site from the template.
 *
 * Usage:
 *   bun new-site.ts \
 *     --service "Emergency Plumber" --phrase "emergency plumbing" \
 *     --city "Gold Coast" --state "Queensland" --state-abbr QLD --postcode 4217 \
 *     --brand "Gold Coast Emergency Plumber Quotes" \
 *     --domain www.emergencyplumbergoldcoast.com \
 *     --email quotes@emergencyplumbergoldcoast.com \
 *     --suburbs "Southport:4215,Surfers Paradise:4217,Burleigh Heads:4220" \
 *     [--phone "07 5555 5555"] [--no-push]
 *
 * Does: copy template → write site.config.ts + data/locations.json →
 * bun install → bun run build (must pass) → git init/commit →
 * create private GitHub repo (PAT from ~/.hermes/.env) → push →
 * register in sites.json → print launch checklist.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { homedir } from "node:os";
import path from "node:path";

const LEADGEN_DIR = path.join(homedir(), "antigravity", "leadgen");
const TEMPLATE_DIR = path.join(LEADGEN_DIR, "template");
const REGISTRY = path.join(LEADGEN_DIR, "sites.json");
const SITES_DIR = path.join(homedir(), "sites");
const GITHUB_USER = "Travissteel";

function arg(name: string, fallback?: string): string {
  const i = process.argv.indexOf(`--${name}`);
  if (i !== -1 && process.argv[i + 1]) return process.argv[i + 1];
  if (fallback !== undefined) return fallback;
  console.error(`Missing required flag: --${name}`);
  process.exit(1);
}

const flags = {
  service: arg("service"),
  phrase: arg("phrase"),
  city: arg("city"),
  state: arg("state"),
  stateAbbr: arg("state-abbr"),
  postcode: arg("postcode"),
  brand: arg("brand"),
  domain: arg("domain"), // expects www host, no protocol
  email: arg("email"),
  suburbs: arg("suburbs"), // "Name:postcode,Name:postcode"
  phone: arg("phone", ""),
  primary: arg("primary", "#0f766e"),
  accent: arg("accent", "#f59e0b"),
};
const noPush = process.argv.includes("--no-push");

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const siteSlug = slugify(flags.domain.replace(/^www\./, "").replace(/\.[a-z.]+$/, ""));
const targetDir = path.join(SITES_DIR, siteSlug);
const domainUrl = `https://${flags.domain.startsWith("www.") ? flags.domain : `www.${flags.domain}`}`;

if (existsSync(targetDir)) {
  console.error(`Target already exists: ${targetDir}`);
  process.exit(1);
}

const suburbs = flags.suburbs.split(",").map((entry) => {
  const [name, postcode = ""] = entry.split(":").map((s) => s.trim());
  return {
    slug: slugify(name),
    name,
    postcode,
    blurb: `${name} is one of the ${flags.city} suburbs where ${flags.brand} arranges free ${flags.phrase} quotes from local professionals.`,
  };
});

console.log(`→ Copying template to ${targetDir}`);
mkdirSync(SITES_DIR, { recursive: true });
cpSync(TEMPLATE_DIR, targetDir, {
  recursive: true,
  filter: (src) => !src.includes("node_modules") && !src.includes(".next"),
});

console.log("→ Writing site.config.ts");
const config = `/**
 * Single source of truth for this site — generated by
 * ~/antigravity/leadgen/scripts/new-site.ts. Every page, schema block, and
 * llms.txt read from here.
 *
 * VOICE RULE (do not remove): this brand is a quote-matching / referral
 * service. Copy must never claim to be a licensed tradesperson, and no
 * reviews, ABNs, or licence numbers may be invented.
 */

export interface SubService {
  slug: string;
  name: string;
  blurb: string;
}

export interface FAQ {
  question: string;
  answer: string;
}

export interface Fact {
  label: string;
  value: string;
}

export interface SiteConfig {
  brandName: string;
  domain: string;
  service: { name: string; phrase: string };
  location: { city: string; state: string; stateAbbr: string; postcode: string };
  email: string;
  phoneDisplay: string;
  theme: { primary: string; accent: string };
  subServices: SubService[];
  faqs: FAQ[];
  facts: Fact[];
}

export const SITE: SiteConfig = ${JSON.stringify(
  {
    brandName: flags.brand,
    domain: domainUrl,
    service: { name: flags.service, phrase: flags.phrase },
    location: {
      city: flags.city,
      state: flags.state,
      stateAbbr: flags.stateAbbr,
      postcode: flags.postcode,
    },
    email: flags.email,
    phoneDisplay: flags.phone,
    theme: { primary: flags.primary, accent: flags.accent },
    subServices: [
      {
        slug: "urgent-callouts",
        name: `Urgent ${flags.service} Call-Outs`,
        blurb: `Fast-response ${flags.phrase} for jobs that can't wait. We connect you with local pros available now.`,
      },
      {
        slug: "quotes-and-inspections",
        name: "Quotes & Inspections",
        blurb: `Planning ahead? Get local ${flags.phrase} professionals to inspect and quote your job for free.`,
      },
    ],
    faqs: [
      {
        question: `How do I get ${flags.phrase} quotes in ${flags.city}?`,
        answer: `Describe your job through ${flags.brand} and licensed local professionals who service ${flags.city} will contact you directly with quotes. The service is free with no obligation.`,
      },
      {
        question: `Does ${flags.brand} do the work itself?`,
        answer: `No. ${flags.brand} is a free quote-matching service — we pass your job details to licensed local professionals who quote and carry out the work.`,
      },
    ],
    facts: [
      { label: "Service area", value: `${flags.city}, ${flags.stateAbbr} and surrounding suburbs` },
      { label: "Cost of a quote", value: "Free — no obligation" },
    ],
  },
  null,
  2
)};

export const CORE_PHRASE = \`\${SITE.service.name} \${SITE.location.city}\`;
`;
writeFileSync(path.join(targetDir, "site.config.ts"), config);

console.log("→ Writing data/locations.json");
writeFileSync(
  path.join(targetDir, "data", "locations.json"),
  JSON.stringify(suburbs, null, 2) + "\n"
);

// The template ships Gold Coast example content in lib/posts.ts and
// lib/faq-pages.ts. Reset both to empty for a fresh site — the nightly cron
// fills them with niche-specific content.
console.log("→ Resetting example content (posts, FAQ colony pages)");
for (const [file, type] of [
  ["lib/posts.ts", "Post"],
  ["lib/faq-pages.ts", "FaqPage"],
] as const) {
  const p = path.join(targetDir, file);
  const src = readFileSync(p, "utf8");
  const marker = `export const ${type === "Post" ? "posts: Post" : "faqPages: FaqPage"}[] = [`;
  const start = src.indexOf(marker);
  const end = src.indexOf("];", start);
  writeFileSync(p, src.slice(0, start + marker.length) + "\n" + src.slice(end));
}

const run = (cmd: string, cwd = targetDir) => {
  console.log(`  $ ${cmd}`);
  execSync(cmd, { cwd, stdio: "inherit" });
};

console.log("→ Installing dependencies");
run("bun install");

console.log("→ Verifying build (must pass before repo creation)");
run("bun run build");

console.log("→ Initialising git repo");
run("git init -b main");
run('git config user.email "travissteel@users.noreply.github.com"');
run('git config user.name "Travis Steel"');
run("git add -A");
run(`git commit -m "Scaffold ${flags.brand} from leadgen template"`);

if (noPush) {
  console.log("⚠ --no-push: skipping GitHub repo creation and push.");
} else {
  const env = readFileSync(path.join(homedir(), ".hermes", ".env"), "utf8");
  const token = env.match(/^GITHUB_TOKEN=(.+)$/m)?.[1]?.trim();
  if (!token) {
    console.error("GITHUB_TOKEN not found in ~/.hermes/.env — cannot create repo.");
    process.exit(1);
  }
  console.log(`→ Creating private GitHub repo ${GITHUB_USER}/${siteSlug}`);
  const res = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      authorization: `Bearer ${token}`,
      accept: "application/vnd.github+json",
    },
    body: JSON.stringify({ name: siteSlug, private: true }),
  });
  if (!res.ok) {
    console.error(`GitHub repo creation failed: ${res.status} ${await res.text()}`);
    process.exit(1);
  }
  run(`git remote add origin https://github.com/${GITHUB_USER}/${siteSlug}.git`);
  run(
    `git -c credential.helper='!f(){ echo username=${GITHUB_USER}; echo password=${token}; };f' push -u origin main`
  );
}

console.log("→ Registering site in sites.json");
const registry = existsSync(REGISTRY)
  ? JSON.parse(readFileSync(REGISTRY, "utf8"))
  : { sites: [] };
registry.sites.push({
  slug: siteSlug,
  domain: domainUrl,
  repo: noPush ? null : `https://github.com/${GITHUB_USER}/${siteSlug}`,
  localPath: targetDir,
  service: flags.service,
  location: `${flags.city}, ${flags.stateAbbr}`,
  status: "scaffolded",
  launchedAt: null,
  lastWorkedAt: null,
  notes: "",
});
writeFileSync(REGISTRY, JSON.stringify(registry, null, 2) + "\n");

console.log(`
✓ ${flags.brand} scaffolded at ${targetDir}

Next steps (see ~/antigravity/leadgen/LAUNCH-CHECKLIST.md):
  1. Buy the domain (${flags.domain.replace("www.", "")}) — aim for the exact-match .com under $30
  2. Vercel → Import Git Repository → ${siteSlug}
  3. Set Vercel env vars: RESEND_API_KEY, LEAD_TO_EMAIL (and LEAD_FROM_EMAIL once the domain is verified in Resend)
  4. Attach the domain with www as canonical
  5. Set status to "live" in leadgen/sites.json + set launchedAt
  6. Submit sitemap in Google Search Console
`);
